### ISSUE TITLE
useUserProvidedYLabels cannot be used as a setting because it is final

### ISSUE THREAD

**Issue by Winghin2517** [mzimmerm/flutter_charts#13]
I have been trying to run the sample code but it is giving me the following error on the line:

     _lineChartOptions.useUserProvidedYLabels = true;

It says:

useUserProvidedYLabels cannot be used as a setting because it is final

Please may you fix.

**Comment by moda20** [comment]
This is still a problem, did anybody figure it out ?

**Comment by mzimmerm** [comment]
@Winghin2517 @moda20  If this is still relevant: Any option can be set in code as follows:

(Caveat: This code is from flutter_charts v. 0.3.0, which is different from the version at the time of the question.)

```dart
            chartOptions = LineChartOptions(
              chartOptions: const ChartOptions(
                yContainerOptions: YContainerOptions(useUserProvidedYLabels: true), // use Y labels below
              ),
            );

```
Please also take a look at https://github.com/mzimmerm/flutter_charts/blob/master/example1/lib/main.dart , search for the example named `ex40LanguagesWithYOrdinalUserLabelsAndUserColors`

**Comment by mzimmerm** [comment]
@Winghin2517 @moda20 Thanks for reporting this. Hopefully the snippet of code above helps with your problem, if it is still relevant. Also the latest version provides lots of examples

https://pub.dev/packages/flutter_charts

I will go ahead and close this, please feel free to reopen if you disagree. Thanks
