### ISSUE TITLE
Running on iOS emulator

### ISSUE THREAD

**Issue by Winghin2517** [mzimmerm/flutter_charts#14]
When running on iOS emulator, the following error is encountered:

> Finished with error: TimeoutException: Request to Dart VM Service timed out: _flutter.listViews({isolateId: isolates/961460569})

This error results in the emulator just displaying a white screen with no graphs on it.

<img width="415" alt="screen shot 2018-06-09 at 09 21 51" src="https://user-images.githubusercontent.com/7094734/41188929-966806b6-6bc6-11e8-8c99-29d75f721d4d.png">

Here is my flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, v0.4.5-pre.56, on Mac OS X 10.13.4 17E202, locale en-ZA)
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
> [!] iOS toolchain - develop for iOS devices (Xcode 9.4)
>     ! CocoaPods out of date (1.5.0 is recommended).
>         CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
>         For more info, see https://flutter.io/platform-plugins
>       To upgrade:
>         brew upgrade cocoapods
>         pod setup
> [✓] Android Studio (version 3.1)
> [!] IntelliJ IDEA Community Edition (version 2016.1.1)
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     ✗ This install is older than the minimum recommended version of 2017.1.0.
> [!] VS Code (version 1.23.1)
> [✓] Connected devices (1 available)
> 
> ! Doctor found issues in 3 categories.

I'm running Flutter through Android Studios.

**Comment by mzimmerm** [comment]
@Winghin2517 Is this still a problem? Can you please provide more details on how you run it - I see from your issue description this was run on Androis Studio IntelliJ. Flutter charts do not use any plugins. Flutter charts do not use any plugins, so it's ability to run on any emulator should not need anything special, iOS or other OS. Are you able to you run other Flutter apps on the same emulator? Flutter charts do not use any plugins, so it's ability to run on any emulator should not need anything special, iOS or other OS.

**Comment by mzimmerm** [comment]
@Winghin2517 Thanks again for reporting this. As I cannot duplicate it, I will go ahead and close this item. Please feel free to reopen if you still see a problem.
