### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by takaoandrew** [mzimmerm/flutter_charts#15]
I'm having trouble seeing bar charts for negative values. The chart seems to scale properly, and the axes are show in the right range, with negative values... The only problem is, the bars themselves do not render. Has anyone been able to see negative values on a bar chart?

**Comment by mzimmerm** [comment]
@takaoandrew If this is still relevant to you, can you please provide more details? I cannot duplicate this so far. Thanks

**Comment by mzimmerm** [comment]
@takaoandrew Please see my comment above. I will go ahead and close this , as negative values do work in general. If you find an issue, would you please reopen with a specific example, thanks
