### ISSUE TITLE
How to display Y axis values in logarithmic scale?

### ISSUE THREAD

**Issue by cassc** [mzimmerm/flutter_charts#22]
If I scale the values manually, the displayed Y axis values would be incorrect.

Thanks!

**Comment by mzimmerm** [comment]
@cassc Sorry for the very late response. If this is still relevant: I am now working on flutter charts again as I need some new features for my stuff. I plan to add Y-scaling using a function soon (within a month or so). 

While I have been so far using the manual Y values (it can be done by log-ging the Y values and displaying the manual Y labels on the original scale but the results are ugly and the Y axis labels, even though correct technically, not really acceptable)

**Comment by om-ha** [comment]
It's nice that `flutter_charts` is implementing this. Having logarithmic scale is very important in my opinion. [Here is why](https://github.com/imaNNeoFighT/fl_chart/issues/434#issuecomment-998828595).

Additionally, here's [an exhaustive list](https://github.com/imaNNeoFighT/fl_chart/issues/434#issuecomment-998847822) mentioning anything about logarithmic scale in flutter charting libraries.

**Comment by mzimmerm** [comment]
@om-ha Thanks for your comments and links. I am working on it.

**Comment by mzimmerm** [comment]
@om-ha : Flutter_charts v 0.4.0 now allow logarithmic scale. Please see the line chart example ex52AnimalsBySeasonLogarithmicScale_lineChart in Readme at this link: 

https://pub.dev/packages/flutter_charts#org369cbfd

Thanks for reporting this.In case you use flutter_charts, please let me know here if there are some issues or things to improve (I am sure about the second)

**Comment by om-ha** [comment]
Thanks for the hard work! Will definitely do.
