### ISSUE TITLE
PieChart放在listview的第一个item报错

### ISSUE THREAD

**Issue by huangxiaoyu** [mzimmerm/flutter_charts#25]
I/flutter (20853): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (20853): The following assertion was thrown during performLayout():
I/flutter (20853): FlutterError contained multiple error summaries.
I/flutter (20853): All FlutterError objects should have only a single short (one line) summary description of the
I/flutter (20853): problem that was detected.
I/flutter (20853): Malformed FlutterError:
I/flutter (20853):   RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (20853):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter (20853):   inside another render object that allows its children to pick their own size.
I/flutter (20853):   RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (20853):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter (20853):   inside another render object that allows its children to pick their own size.
I/flutter (20853):   The nearest ancestor providing an unbounded height constraint is: RenderIndexedSemantics#c2871 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (20853):     creator: IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ←
I/flutter (20853):       AutomaticKeepAlive ← KeyedSubtree ← SliverList ← MediaQuery ← SliverPadding ← Viewport ←
I/flutter (20853):       IgnorePointer-[GlobalKey#f9e30] ← Semantics ← Listener ← ⋯
I/flutter (20853):     parentData: index=0; layoutOffset=0.0 (can use size)
I/flutter (20853):     constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
I/flutter (20853):     semantic boundary
I/flutter (20853):     size: MISSING
I/flutter (20853):     index: 0
I/flutter (20853):   The constraints that applied to the RenderCustomMultiChildLayoutBox were:
I/flutter (20853):     BoxConstraints(w=360.0, 0.0<=h<=Infinity)
I/flutter (20853):   The exact size it was given was:
I/flutter (20853):     Size(360.0, Infinity)
I/flutter (20853):   See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.
I/flutter (20853): 
I/flutter (20853): The malformed error has 2 summaries.
I/flutter (20853): Summary 1: RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (20853): Summary 2: RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (20853): 
I/flutter (20853): This error should still help you solve your problem, however please also report this malformed error
I/flutter (20853): in the framework by filing a bug on GitHub:
I/flutter (20853):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20853): 
I/flutter (20853): When the exception was thrown, this was the stack:
I/flutter (20853): #0      new FlutterError.fromParts.<anonymous closure> (package:flutter/src/foundation/assertions.dart:540:9)
I/flutter (20853): #1      new FlutterError.fromParts (package:flutter/src/foundation/assertions.dart:543:6)
I/flutter (20853): #2      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1966:28)
I/flutter (20853): #3      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2029:6)
I/flutter (20853): #4      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1740:7)
I/flutter (20853): #5      RenderBox.size= (package:flutter/src/rendering/box.dart:1742:6)
I/flutter (20853): #6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:5)
I/flutter (20853): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #12     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter (20853): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #14     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter (20853): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #16     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter (20853): #17     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter (20853): #18     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter (20853): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #38     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (20853): #39     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter (20853): #40     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (20853): #41     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (20853): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #46     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (20853): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20853): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #62     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3074:14)
I/flutter (20853): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20853): #64     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (20853): #65     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter (20853): #66     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (20853): #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (20853): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (20853): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (20853): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (20853): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (20853): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (20853): #76     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (20853): #77     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (20853): (elided 3 frames from package dart:async)
I/flutter (20853): 
I/flutter (20853): The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#dc822 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (20853):   creator: CustomMultiChildLayout ← PieChart<dynamic> ← RepaintBoundary ← IndexedSemantics ←
I/flutter (20853):     NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ←
I/flutter (20853):     SliverList ← MediaQuery ← SliverPadding ← Viewport ← ⋯
I/flutter (20853):   parentData: <none> (can use size)
I/flutter (20853):   constraints: BoxConstraints(w=360.0, 0.0<=h<=Infinity)
I/flutter (20853):   size: Size(360.0, Infinity)
I/flutter (20853): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (20853):     child 1: RenderSemanticsGestureHandler#25afc NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20853):       child: RenderPointerListener#3f173 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20853):         child: ChartContainerRenderObject<dynamic>#7318a NEEDS-LAYOUT NEEDS-PAINT
I/flutter (20853): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by huangxiaoyu** [comment]
我的代码,这个代码会报上面的错误  
child: ListView.builder(
          physics: NeverScrollableScrollPhysics(),
          controller: scList,
          itemBuilder: (context, index) {
            if (index > 0 && index < listData.length+1) {
              return Card(
                elevation: 5,
                shape: RoundedRectangleBorder(
                    side: BorderSide(width: 0.6, color: Colors.grey),
                    borderRadius: BorderRadius.all(Radius.circular(5))),
                margin: EdgeInsets.all(4),
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => PageAlarmInfo(
                                  type: type,
                                  fid: listData[index-1].FID,
                                )));
                  },
                  child: Container(
                    padding: EdgeInsets.all(8),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Text("单位名称: ${listData[index-1].DEPTNAME}"),
                        Text("警情描述: ${listData[index-1].DESP}"),
                        Text(
                            "当前状态: ${listData[index-1].FLAG == 1 ?
                        listData[index+1].DISPOSAL : '未处理'}"),
                        Text("接警时间: ${listData[index-1].REVTIME}"),
                        Text("报警时间: ${listData[index-1].HAPTIME}"),
                      ],
                    ),
                  ),
                ),
              );
            } else if(index==0) {
              return charts.PieChart(seriesList, animate: false);
            } else {
              return mPage.refreshEnable ? LoadmoreView() : LoadAllView();
            }
          },
          itemCount: listData.length + 2,
        ),

**Comment by mzimmerm** [comment]
You must be reporting against another library. This one does not have PieCharts yet. Closing
