### ISSUE TITLE
当我使用setState((){})刷新页面时，该数值消失

### ISSUE THREAD

**Issue by Jinxishihenian** [mzimmerm/flutter_charts#27]
![深度截图_选择区域_20191017100252](https://user-images.githubusercontent.com/44466363/66972059-ea33d600-f0c5-11e9-8e0e-b423327894eb.png)

**Comment by mzimmerm** [comment]
Can you add details - are you requesting to show values on top of the bar?

**Comment by mzimmerm** [comment]
This appears reported to another library , charts_flutter.
