### ISSUE TITLE
Did you give up?

### ISSUE THREAD

**Issue by nipunasudha** [mzimmerm/flutter_charts#32]
Did you give up on this awesome flutter plugin?

**Comment by mzimmerm** [comment]
Hi, thanks for your comment. Sorry to all who may be using flutter_charts, for not being responsive. 

To answer this direct question, I did not give up, but had lots of other work last few years. 

Having said that, I am, for a while now, planning to get back to move flutter_charts to the latest Flutter, and start working on it again. 

As I am just finishing up a project, I should get back to flutter_chart very soon now (before end of November), then should dedicate some fixed hours every week for a period after.

Thanks
Milan

**Comment by nipunasudha** [comment]
Thats great news! we are looking forward. thank you!
