### ISSUE TITLE
View seconds in timeseries chart

### ISSUE THREAD

**Issue by danielle-h** [mzimmerm/flutter_charts#35]
I am using flutter_charts to plot data online that I receive from a sensor at 6Hz. The graph is great, but I found no way to show the seconds in the X axis as AutoDateTimeTickFormatterSpec does not have a seconds option. I tried using a linechart instead with the number of seconds since start, but the graph does not scroll (removing points does not cause the X axis to update bounds).Am I missing something? Is there an existing way of doing this?

Thanks!

**Comment by mzimmerm** [comment]
Are you using flutter_charts or charts_flutter? AutoDateTimeTickFormatterSpec does not sound like it is flutter_charts.

**Comment by danielle-h** [comment]
You are correct, sorry :)
