### ISSUE TITLE
Fractional support on y axis

### ISSUE THREAD

**Issue by MichaelRFairhurst** [mzimmerm/flutter_charts#4]
Hey again Milan,

I noticed that it seems like the data points get aligned to a tick on the y axis. Is there a way to turn this off?

**Comment by mzimmerm** [comment]
Hi Michael,

All useful things! Although on this one I am not quite sure what you mean. Do you need to not show the y labels, or align them differently (below, above the y tick?) Let's try to describe this, or if you have a quick screenshot with a comment that may work best.

Milan

**Comment by MichaelRFairhurst** [comment]
This turned out to be a bug in my own code! Was accidentally rounding somewhere.

**Comment by mzimmerm** [comment]
Thanks for the follow up Michael.
