### ISSUE TITLE
Coloring support for points in line chart

### ISSUE THREAD

**Issue by MichaelRFairhurst** [mzimmerm/flutter_charts#5]
Hey Milan,

it looks like I can change the size of the points on the line chart (inner radius, outer radius). Is there a way I can change the color as well?

**Comment by mzimmerm** [comment]
Without looking at the code, I think this is hardcoded :( - High on the priority list, this weekend OK for the mini enhancement?

**Comment by MichaelRFairhurst** [comment]
Any weekend (this, next...) would be great to see this :)

**Comment by mzimmerm** [comment]
@MichaelRFairhurst : Michael, I published a new version that addresses and should fix items 5, 6. Please take a look at https://pub.dartlang.org/packages/flutter_charts#pub-pkg-tab-changelog for details. 

Let me know if there are some issues with the two.

I started working on item 3 (planning for now by a simple iterative X labels layout that will either/or tilt/skip labels.
Later,
Milan

**Comment by MichaelRFairhurst** [comment]
This also works great. Glad to see so many new options!
