### ISSUE TITLE
pub.dartlang.org fails to load README images

### ISSUE THREAD

**Issue by asaarnak** [mzimmerm/flutter_charts#8]
At: 
https://pub.dartlang.org/packages/flutter_charts#-readme-tab-
The README docs images are not loaded.

**Comment by asaarnak** [comment]
Following url is tried:
https://pub.dartlang.org/packages/doc/readme_images/README.org_20171102_180915_270634jy.png 404 ()

**Comment by mzimmerm** [comment]
Thanks for reporting. This is now fixed in the new version - Images in the README.md should now show at https://pub.dartlang.org/packages/flutter_charts . (I keep the latest README in org format, converting to markdown before publishing, and I forgot a step).

**Comment by asaarnak** [comment]
Thanks, looks good.
